In [1]:
#Libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
#Loading dataset
df_homes = pd.read_csv('homeprices.csv')
df_homes

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Here, We can see that our data has one NaN entry that means, its value is not a number or undefined.

Here, we need to do some **Data Pre-Processing** as,we need numerical value for this to train our model.

There are multiple ways to assume that NaN value but here we are going to replace it with median of other values.

In [10]:
median = df_homes.bedrooms.median()
median

4.0

In [11]:
df_homes.bedrooms = df_homes.bedrooms.fillna(median)
df_homes

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Now, our NaN is replaced with our median.

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df_homes.drop('price',axis='columns').values,df_homes.price) 
#In our first arugemnt we are taking all three columns of data except price.
#Price in depedent variable and other three are independent.

LinearRegression()

In [19]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

Here, we have three Coefficients for aur three independent variables.

In [20]:
reg.intercept_

221323.00186540384

In [23]:
#Finding price of home with 3200 sqr ft area, 4 bedrooms, 20 year old
reg.predict([[3200, 4, 20]])

array([608843.97821933])

In [24]:
# Calculating by equation y = m1x1 + m2x2 + m3x3 +b
# where m1,m2,m3 are aruguments of relevant features, area,bedrooms and age respectively. And b is intercept.
reg.coef_[0]*3200 + reg.coef_[1]*4 + reg.coef_[2]*20 + reg.intercept_

608843.9782193323

In [25]:
#Find price of home with 4500 sqr ft area, 5 bedrooms, 5 year old
reg.predict([[4500, 5, 5]])

array([826389.80145154])